### ISSUE TITLE
Optimize font loading strategy to improve performance

### ISSUE THREAD

**Issue by julianpinedayyz** [julianpinedayyz/portfolio#8]
## Description
The performance audit reveals that the site is loading 6 font files, which contributes to slower loading times. Font loading can be a significant factor affecting FCP and LCP metrics.

## Current State
- 6 font requests detected
- Fonts may be contributing to delayed First Contentful Paint (1941ms)
- Inter font is currently being loaded from external source (rsms.me)

## Proposed Solution
1. Implement font-display strategies to prevent font-based render blocking:
   ```css
   @font-face {
     font-family: 'Inter';
     font-style: normal;
     font-weight: 400;
     font-display: swap; /* Show fallback font immediately while custom font loads */
     src: url('/fonts/inter-regular.woff2') format('woff2');
   }
   ```

2. Consider self-hosting critical font files to eliminate third-party dependency:
   - Download and host the most frequently used weights of Inter
   - Use a variable font file if possible to reduce multiple requests

3. Reduce the number of font weights being loaded:
   - Audit which weights are actually being used
   - Eliminate unused weights

## Expected Outcome
- Faster initial text rendering with font-display: swap
- Reduced network requests by consolidating font files
- Improved FCP and LCP times
- Better performance on slower connections

## Complexity
Low - Simple CSS/font configuration changes

## Related Audit
Performance audit - Total font requests: 6
